# Generated by Django 2.2.6 on 2021-05-05 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('desc', models.TextField(null=True, verbose_name='Category Description')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.FileField(upload_to='./media', verbose_name='Art Image')),
                ('name', models.CharField(max_length=50, verbose_name='Art Name')),
                ('desc', models.TextField(null=True, verbose_name='Art Description')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Art Author')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AP.Category', verbose_name='Art Category')),
            ],
        ),
    ]
